# Generated by Django 5.2.5 on 2025-08-13 11:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_type', models.CharField(choices=[('historical_posts', 'Historical Posts'), ('user_posts', 'User Posts'), ('category_posts', 'Category Posts')], max_length=50)),
                ('file_format', models.CharField(default='json', max_length=10)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('request_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('filters_applied', models.JSONField(blank=True, default=dict)),
                ('total_records', models.PositiveIntegerField(default=0)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('processing_time_seconds', models.FloatField(default=0.0)),
                ('is_successful', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['user', 'requested_at'], name='downloads_d_user_id_49f8dc_idx'), models.Index(fields=['download_type', 'requested_at'], name='downloads_d_downloa_d9611b_idx')],
            },
        ),
    ]
